ROOT = path.getabsolute("./").."/"
include("premake/premake.utils.lua")
workspace "nvigi"
include("premake/premake.shared_config.lua")
include("premake/premake.shared_plugin.lua")
include("premake/premake.cuda_utils.lua")
include("source/plugins/nvigi.aip/premake.lua")
include("source/plugins/nvigi.asr/ggml/premake.lua")
include("source/plugins/nvigi.embed/ggml/premake.lua")
include("source/plugins/nvigi.gpt/ggml/premake.lua")
include("source/plugins/nvigi.gpt/rest/premake.lua")
include("source/plugins/nvigi.net/premake.lua")
include("source/plugins/nvigi.tts/asqflow/ggml/premake.lua")
include("source/plugins/nvigi.tts/asqflow/trt/premake.lua")
include("source/samples/nvigi.3d/premake.lua")
include("source/samples/nvigi.basic/premake.lua")
include("source/samples/nvigi.fcall/premake.lua")
include("source/samples/nvigi.pipeline/premake.lua")
include("source/samples/nvigi.rag/premake.lua")
include("source/samples/nvigi.reload/premake.lua")
